### ISSUE TITLE
"Fill all available space" solution for container size

### ISSUE THREAD

**Issue by Manishearth** [rust-fuzz/arbitrary#18]
Broadly, there are two kinds of things Arbitrary generates. Fixed-size objects that map to a fixed set of integers, and variable size objects, which can use something like `container_size()`.

Thing is, unlike, say, quickcheck, we already have a finite number of bytes as input. It would be nice if Arbitrary could be told "hey, I only have X bytes of data and you're my last consumer" as opposed to "slurp as much data as you want, I'll split the difference amongst the next consumers!"

This seems pretty tricky to design in the general case, but we could initially settle for types like `String` and `Vec` just filling directly.

**Comment by Manishearth** [comment]
I think I figured this out! Your commit in #20 gave me a hint, and perhaps you have this plan already. There are two ways to do this, one static, one dynamic.

The static one involves tweaking `Arbitrary` into two methods:

```rust
trait Arbitrary {
  fn arbitrary(u: &mut Unstructured) -> Self;
  fn arbitrary_take_rest(u: TakeRest) -> Self { Self::arbitrary(u.as_unstructured()) } 
}
```

`TakeRest` is like `Unstructured`, but exposes the byte slice directly, and is also consumed. You can temporarily obtain an `Unstructured` from a `TakeRest` with (`fn as_unstructured(&mut self) -> &mut Unstructured`), but you can't go the other way around unless you have an owned handle to the `Unstructured`.

```rust
struct TakeRest {
   u: Unstructured
}

impl TakeRest {
   fn new(u: Unstructured) -> Self;
   fn as_unstructured(&mut self) -> &mut Unstructured;
   fn bytes(&self) -> &[u8];
}
```



Fixed-size (by size I'm talking about size in terms of _information_ -- i.e. input bytes, not layout bytes) types don't do anything special for `arbitrary_take_rest` and use the default forwarding impl.

Variable sized types implement `arbitrary_take_rest` by actually using the length available on the `TakeRest`. So String will just slurp up all the available bytes as utf8 (failing if it doesn't parse). They implement `arbitrary()` normally, using `container_size()`.

Structured data that _may_ contain variable-sized fields implements `arbitrary_take_rest` by using `as_unstructured` and constructing all but the last subfield normally, and _then_ calling `arbitrary_take_rest` to construct the last subfield.

Generic collections are still interesting, Vec won't know when to stop! Ideally we want `Vec<u8>` and `HashSet<u8>` to just parse all the `u8`s, but that's tricky to make work in a world that _also_ has `Vec<String>`. One way to do this is to add a `size_hint` function that in the case of fixed size types returns the size, but in the case of variable size types returns `None`. So the `arbitrary_take_rest` implementation for Vec would, in the case of a `Some` `size_hint`, chunk by that size hint and then just call `arbitrary()` `n` times, and in the case of `None` give up and use `container_size`, and then call `arbitrary_take_rest` for the last element.


The dynamic design is _essentially_ the same as the static one, except it's done by a boolean argument to `arbitrary` instead of two methods, and you have fewer protections from types. I prefer the static one just because I expect it would optimize out most of the cruft, but it does prove to be a hindrance for manual trait implementors (I suspect these will be rare?)

**Comment by fitzgen** [comment]
Of the two designs, I would also lean towards the static/two method version. I also agree that the goal is desirable: not leaving input behind that we could have meaningfully used. I can even imagine pathological situations where we don't use the last N bytes of input, and the fuzzer keeps mutating those bytes that we aren't using, and then we keep not using those and running the exact same execution as last time, and fuzzing becomes pretty inefficient. Not good.

However, I also have two concerns:

1. **Cognitive overhead of a more complicated trait.** I don't think there is much to expand on this point. If we are going to make the trait more complicated, that implies a learning cost that every single user will have to pay, so we should only do this if we really get a lot of value out of it.

2. **Usability in the face of composition.** This trait is almost exclusively used by combining smaller `Arbitrary` implementations into larger ones, and very few people are writing "leaf" `Arbitrary` implementations by hand. Mostly just us with out implementations for `std` types. Users will typically have a single `Arbitrary` type at the top level and they do something like

````rust
let input = MyType::arbitrary(&mut unstructured)?;
do_fuzz(input);
```

Would that turn into this?

```rust
let input = MyType::arbitrary_take_rest(&mut unstructured)?;
do_fuzz(input);
```

What if `MyType` is composed of multiple other `Arbitrary` things that it composes?

```rust
#[derive(Arbitrary)]
struct MyType {
    y: Vec<u8>,
    z: String,
}
```

In this situation, assuming we are creating `y` and then creating `z`, we want `z` to use `arbitrary_take_rest` *iff* we are in `MyType::arbitrary_take_rest` and we always want `y` to be created with `arbitrary`.

Actually that doesn't as bad as I was originally imagining. And I just realized this is exactly what you're saying here:

> Structured data that _may_ contain variable-sized fields implements `arbitrary_take_rest` by using `as_unstructured` and constructing all but the last subfield normally, and _then_ calling `arbitrary_take_rest` to construct the last subfield.

So yeah, okay I think I like this.

We would have a default impl of `arbitrary_take_rest` that just runs `Arbitrary`, yeah. I think that would soften point (1) a bit, since you could generally ignore it unless writing `Arbitrary` implementations by hand or writing the fuzz driver integration code where you would want to call the `arbitrary_take_rest` version at the top level (eg the `libfuzzer-sys` crate).

-----------------------------------

> You can temporarily obtain an `Unstructured` from a `TakeRest` with (`fn as_unstructured(&mut self) -> &mut Unstructured`), but you can't go the other way around unless you have an owned handle to the `Unstructured`.

This is neat. So the top level will pass in `TakeRest` by value and then everyone else works with `&mut Unstructured` except the last fields, which get `TakeRest` by value as well. Nice.

-------------------------

> One way to do this is to add a `size_hint` function that in the case of fixed size types returns the size, but in the case of variable size types returns `None`

I've also been thinking about a size hint type of method, since we can give you `n` bytes, but that most likely can't construct `n` elements for your container, since almost everything requires more than `n` bytes.

I think we actually want to match `Iterator::size_hint` a little more closely, where we return `(min, Option<max>)`. This would let us express "I need at least `n` bytes for my fixed-size fields, but I also have variably-sized fields". And then containers could be a little conservative and do something like `num_elements = raw_container_size /  min * 2`.

We might even want `container_size` to be parameterized by the element type:

```rust
fn container_size<A>(&mut self) -> Result<usize>
where
    A: Arbitrary
{
    let num_bytes = current_container_size_implementation();
    let (min, max) = A::size_hint();
    let elem_size = max.unwrap_or_else(|| min * 2);
    let elem_size = std::cmp::max(elem_size, 1);
    Ok(num_bytes / elem_size)
}
```

While we're at it, I'm not a huge fan of the name `container_size`... what do you think of `collection_len`? Personally, I find "collection" more intuitive than "container", since a `Box` is also a container in some sense, but what we are really after is the variably-sized connotation, which I think "collection" has more of. And for "len", well this is the standard size-of-a-collection method per Rust style, which is the thing we are generating, so I think it makes sense. Maybe "size" makes more sense when talking about bytes and byte sizes, but if we do the parameterization, then I think "len" makes a lot more sense.

--------------------------------------------

Ok finally -- and I'm sorry I'm nitpicking so much over naming, I know I'm doing it but I can't stop myself -- I feel like we could come up with some better names for `TakeRest`, in particular when we consider that it is a dual to `Unstructured`. Nothing about their names tells me they're related.

In fact, what if we didn't have `TakeRest`, we only had

```rust
fn arbitrary(&mut Unstructured) -> Result<Self>;
fn arbitrary_take_rest(Unstructured) -> Result<Self>;
```

?

We would lose the ability to hide the get-the-rest-of-the-underlying-slice method from regular `arbitrary` methods, but we simplify the interface a little bit. Seems like a fine trade off to me.

**Comment by Manishearth** [comment]
> Actually that doesn't as bad as I was originally imagining. And I just realized this is exactly what you're saying here:

Yep, it's not too complicated, and most consumers should be using the derive anyway!

Agree with all the improvements on size_hint and container_size, and I merged the PR making those, thanks for that!

> In fact, what if we didn't have TakeRest, we only had

Oh, yeah, we don't _actually_ need separate types. I don't care much about the naming.

> We would lose the ability to hide the get-the-rest-of-the-underlying-slice method from regular arbitrary methods, but we simplify the interface a little bit. Seems like a fine trade off to me.

Not quite, we can still make obtaining the full slice a `self` method :) But I don't think this is super important.

**Comment by Manishearth** [comment]
> While we're at it, I'm not a huge fan of the name container_size... what do you think of collection_len?

Oh, also, an incremental improvement we can do on this is `for_collection<Element>(&mut self) -> (usize, &[u8])` which automatically handles advancing and stuff. May not be worth it since you can just write this yourself very easily.

**Comment by Manishearth** [comment]
Another QoL thing would be to have a way of getting an iterator over items so that impls for custom containers just become `arbitrary_iter().collect()` (avoiding an allocation with vec)

I might add these when i'm properly online.

**Comment by Manishearth** [comment]
I've started hacking on this in the TakeRest branch
