### ISSUE TITLE
Issue re-strutcturing Vec<u8> from a libfuzz test

### ISSUE THREAD

**Issue by RCasatta** [rust-fuzz/arbitrary#60]
I've got a simple fuzz test
```
fuzz_target!(|data: Vec<u8>| {
    if data.len() > 1 {
        panic!("asfa");
    }
});
```
launching with `cargo fuzz` and libfuzzer I've got
```
SUMMARY: libFuzzer: deadly signal
...
Base64: BB8fHx8qKv//
...

fuzz/artifacts/test/crash-327090b23ecd21b1ed2a745974e0df92e975c3ee

Output of `std::fmt::Debug`:

        [
            186,
            186,
            186,
            10,
            186,
            10,
            0,
            0,
         ]
```

If I want to use this data in a test
```
use arbitrary::Arbitrary;
        let a = base64::decode("BB8fHx8qKv//").unwrap();
        let mut b = arbitrary::Unstructured::new(&a[..]);
        let c = <Vec<u8>>::arbitrary(&mut b);
        dbg!(c);
```
I've got
```
[src/fuzz.rs:90] c = Ok(
    [],
)
```

same if I use
```
        let a = include_bytes!("../fuzz/artifacts/test/crash-327090b23ecd21b1ed2a745974e0df92e975c3ee");
```

This doesn't happen without using Vec

arbitrary version is v0.4.7 on the base project and in the fuzz project

**Comment by nagisa** [comment]
You may want to check either the implementation of [`fuzz_target!`](https://github.com/rust-fuzz/libfuzzer/blob/104fca0a97b7172a0f2b88c4629f5473f7c84fe1/src/lib.rs#L117) and replicate it, or not use `fuzz_target!` at all, so that it is obvious that the tests you have match your fuzzers.

This is also most plausibly not a `arbitrary` issue, so I'm going to close it, both the `fuzz_target` and the base64-encoded data come from libfuzzer (linked above).

**Comment by RCasatta** [comment]
my issue was using:
```
        let c = <Vec<u8>>::arbitrary(&mut b);
```
instead of
```
        let c = <Vec<u8>>::arbitrary_take_rest(b);
```

since `fuzz_target!` call that method https://github.com/rust-fuzz/libfuzzer/blob/104fca0a97b7172a0f2b88c4629f5473f7c84fe1/src/lib.rs#L157
