### ISSUE TITLE
fill_buffer doesn't match doc - never returns NotEnoughData so can't re-fill arbitrary

### ISSUE THREAD

**Issue by Ten0** [rust-fuzz/arbitrary#92]
The `fill_buffer` documentation specifies:
https://github.com/rust-fuzz/arbitrary/blob/e0a5bc777b99a2a17845d1da4ace7e43aacace85/src/unstructured.rs#L392-L393

However the actual implementation is:
https://github.com/rust-fuzz/arbitrary/blob/e0a5bc777b99a2a17845d1da4ace7e43aacace85/src/unstructured.rs#L406-L414
Which silent-fails and never returns an error.

This in turn implies that code such as:
```rust
let line: SomeStructThatDerivesArbitrary = match unstructured.arbitrary() {
	Ok(ok) => ok,
	Err(arbitrary::Error::NotEnoughData) => {
		std::mem::drop(unstructured);
		random_data.clear();
		let mut trng = rand::thread_rng();
		random_data.extend(
			(0..1000)
				.map(|_| trng.sample::<u8, _>(rand::distributions::Standard)),
		);
		unstructured = arbitrary::Unstructured::new(&random_data);
		unstructured.arbitrary()?
	}
	Err(e) => return Err(e.into()),
};
```
actually always generates the same `SomeStructThatDerivesArbitrary` once the initial `arbitrary::Unstructured` is empty. (Which in my case is right at the start.)

`fill_buffer` should match the doc and return `NotEnoughData` when too small instead of silent-fail-ing, otherwise there's a huge risk that the user will actually explore a much smaller space of arbitrary values than they expected.

I note this was initially the case, but was changed in https://github.com/rust-fuzz/arbitrary/commit/1d2f65360f634968b5525f4d6430a88a376277f0.

This commit makes the assumption that fuzzers will reduce their inputs by reducing the number of input bytes, and couldn't perform reduction by turning some input bytes into zeroes - which I think would probably be the correct thing for them to do when using `arbitrary`.

**Comment by Manishearth** [comment]
From that commit:

> Next breaking release that we make, I think we can remove the fallibility from
> the `Arbitrary` trait and all the `Unstructured` methods. The only tricky one is
> `Unstructured::get_bytes`, but I think we can either loosen its contract so that
> it doesn't always return a slice of length `size`, or remove the method
> completely in favor of `Unstructured::fill_buffer`.

So I think @fitzgen intends to get rid of the fallibility here?

**Comment by Ten0** [comment]
> This is an intentional change and that commit's message describes the motivation for this trade off

Given that I pointed the commit myself I know this ^^'

The issue was about having the answer to:


> This commit makes the assumption that fuzzers will reduce their inputs by reducing the number of input bytes, and couldn't perform reduction by turning some input bytes into zeroes - which I think would probably be the correct thing for them to do when using `arbitrary`.

and

> Though I feel like this particular flavor of fallibility does not hurt mutations.

So it's not really "resolved".

**Comment by fitzgen** [comment]
> This commit makes the assumption that fuzzers will reduce their inputs by reducing the number of input bytes, and couldn't perform reduction by turning some input bytes into zeroes - which I think would probably be the correct thing for them to do when using `arbitrary`.

It isn't that we are assuming that fuzzers can't turn input bytes into zeros. Of course they can. We found that in practice, with large and complex `Arbitrary` implementations like [`wasm-smith`](https://crates.io/crates/wasm-smith), we get much better test case reduction via `cargo fuzz tmin` with the "fill with zeroes" approach. That was evidence we used when weighing and choosing the trade off.

> Though I feel like this particular flavor of fallibility does not hurt mutations.

The problem is that all integer `Arbitrary` implementations are based on `fill_buffer`. So we would have to update that code to use zero if there was an error. And that alone isn't hard, but it creates the cognitive burden of having to remember to do this dance every time we introduce a new call to this method, to make sure we do the right thing. Instead, we can do the right thing once, inside `fill_buffer`, and never worry about it again.

-----------------------------------------

In general, I think we should remove `fill_buffer`, or make it an internal implementation detail. External users are better served by `Unstructured::bytes`, where they can choose what to do with the data rather than having `fill_buffer`'s copy foisted upon them 100% of the time.

**Comment by Ten0** [comment]
> We found that in practice, with large and complex `Arbitrary` implementations like [`wasm-smith`](https://crates.io/crates/wasm-smith), we get much better test case reduction

But for this case, couldn't the fuzzer, or its interface with `arbitrary` be parametrized to perform reduction not by lowering the amount of bytes, but by setting them to zero? (in the case where the fuzzer itself doesn't support it, the interface with Arbitrary could enlarge the input used by arbitrary and set the rest to zeroes if that performs better)

It looks like this would also solve the problem (exact same behavior as now), while avoiding silent fails, which notably becomes an issue in more general uses than fuzzing (e.g., [the example above](https://github.com/rust-fuzz/arbitrary/issues/92#issue-1052985185)).

I think without these kind of changes, this enables this library to be used in a wider range of uses than fuzzing, which its name lets suppose it could be used for, while moving in this direction makes it unusable for just generating random inputs, which could be used in benchmarking tools, etc.
